/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface;

import db.interfaces.DBManager;
import db.sqlite.SQLiteManager;
import dementia_dss.Patient;

/**
 *
 * @author adria
 */
public class Alzheimer_Phase extends javax.swing.JPanel {

    DBManager dbManager = new SQLiteManager();
    Patient patient = new Patient();

    /**
     * Creates new form Alzheimer_Phase
     */
    public Alzheimer_Phase() {
        initComponents();
    }

    public Alzheimer_Phase(DBManager dbManager, Patient patient) {
        this.dbManager = dbManager;
        this.patient = patient;
        initComponents();
        String stiffness = (String) Stiffness_box.getSelectedItem();
        if (stiffness.equals("Low")) {
            patient.setStiffnessL("TRUE");
            patient.setStiffnessH("FALSE");
        } else if (stiffness.equals("High")) {
            patient.setStiffnessL("FALSE");
            patient.setStiffnessH("TRUE");
        } else {
            patient.setStiffnessL("FALSE");
            patient.setStiffnessH("FALSE");
        }
        Boolean hyperreflexia = Hyperreflexia_check.isSelected();
        if (hyperreflexia) {
            patient.setHyperreflexia("TRUE");
        } else {
            patient.setHyperreflexia("FALSE");
        }
        Boolean lossPhysicalAbilities = LossPhysicalAbilities_check.isSelected();
        if (lossPhysicalAbilities) {
            patient.setLossPhysicalAbilities("TRUE");
        } else {
            patient.setLossPhysicalAbilities("FALSE");
        }
    }

    public void SaveInfo() {
        Boolean hyperreflexia = this.Hyperreflexia_check.isSelected();
        if (hyperreflexia) {
            patient.setHyperreflexia("TRUE");
        } else {
            patient.setHyperreflexia("FALSE");
        }
        Boolean physicalAbilities = this.LossPhysicalAbilities_check.isSelected();
        if (physicalAbilities) {
            patient.setLossPhysicalAbilities("TRUE");
        } else {
            patient.setLossPhysicalAbilities("FALSE");
        }
        if (physicalAbilities) {
            patient.setLossPhysicalAbilities("TRUE");
        } else {
            patient.setLossPhysicalAbilities("FALSE");
        }
        if (Stiffness_box.getSelectedItem().equals("High")) {
            patient.setStiffnessH("TRUE");
            patient.setStiffnessL("FALSE"); // Lo ponemos a false o lo dejamos en true porque si es high tb es low?
        } else if (Stiffness_box.getSelectedItem().equals("Low")) {
            patient.setStiffnessH("FALSE");
            patient.setStiffnessL("TRUE");
        } else if (Stiffness_box.getSelectedItem().equals("None")) {
            patient.setStiffnessH("FALSE");
            patient.setStiffnessL("FALSE");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Hyperreflexia_check = new javax.swing.JCheckBox();
        LossPhysicalAbilities_check = new javax.swing.JCheckBox();
        Stiffness_box = new javax.swing.JComboBox<>();

        setPreferredSize(new java.awt.Dimension(1260, 777));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Alzheimer Specific Symptoms");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(394, 21, -1, -1));

        jLabel2.setText("Please, mark the present symptoms for the system to be able to estimate the phase:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 68, -1, -1));

        jLabel3.setText("Stiffness");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(532, 148, -1, -1));

        Hyperreflexia_check.setText("Hyperreflexia");
        add(Hyperreflexia_check, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 144, -1, -1));

        LossPhysicalAbilities_check.setText("Loss of physical abilities");
        add(LossPhysicalAbilities_check, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 254, -1, -1));

        Stiffness_box.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Low", "High" }));
        add(Stiffness_box, new org.netbeans.lib.awtextra.AbsoluteConstraints(662, 145, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox Hyperreflexia_check;
    private javax.swing.JCheckBox LossPhysicalAbilities_check;
    private javax.swing.JComboBox<String> Stiffness_box;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
