/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface;

import dementia_dss.Patient;

/**
 *
 * @author adria
 */
public class Alzheimer_Phase extends javax.swing.JPanel {

    Patient patient = new Patient();

    /**
     * Creates new form Alzheimer_Phase
     */
    public Alzheimer_Phase() {
        initComponents();
    }

    public Alzheimer_Phase(Patient patient) {
        this.patient = patient;
        initComponents();
        String stiffness = (String) Stiffness_box.getSelectedItem();
        if (stiffness.equals("Low")) {
            patient.setStiffnessL("TRUE");
            patient.setStiffnessH("FALSE");
        } else if (stiffness.equals("High")) {
            patient.setStiffnessL("FALSE");
            patient.setStiffnessH("TRUE");
        } else {
            patient.setStiffnessL("FALSE");
            patient.setStiffnessH("FALSE");
        }
        Boolean hyperreflexia = Hyperreflexia_check.isSelected();
        if (hyperreflexia) {
            patient.setHyperreflexia("TRUE");
        } else {
            patient.setHyperreflexia("FALSE");
        }
        Boolean lossPhysicalAbilities = LossPhysicalAbilities_check.isSelected();
        if (lossPhysicalAbilities) {
            patient.setLossPhysicalAbilities("TRUE");
        } else {
            patient.setLossPhysicalAbilities("FALSE");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Hyperreflexia_check = new javax.swing.JCheckBox();
        LossPhysicalAbilities_check = new javax.swing.JCheckBox();
        Stiffness_box = new javax.swing.JComboBox<>();

        setPreferredSize(new java.awt.Dimension(1260, 777));

        jLabel1.setText("Alzheimer Specific Symptoms");

        jLabel2.setText("Please, mark the present symptoms for the system to be able to estimate the phase:");

        jLabel3.setText("Stiffness");

        Hyperreflexia_check.setText("Hyperreflexia");

        LossPhysicalAbilities_check.setText("Loss of physical abilities");

        Stiffness_box.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Low", "High" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LossPhysicalAbilities_check)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(Hyperreflexia_check)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3)
                                    .addGap(51, 51, 51)
                                    .addComponent(Stiffness_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(80, 80, 80))
                                .addComponent(jLabel2))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(394, 394, 394)
                        .addComponent(jLabel1)))
                .addContainerGap(237, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Hyperreflexia_check)
                    .addComponent(Stiffness_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(75, 75, 75)
                .addComponent(LossPhysicalAbilities_check)
                .addContainerGap(335, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox Hyperreflexia_check;
    private javax.swing.JCheckBox LossPhysicalAbilities_check;
    private javax.swing.JComboBox<String> Stiffness_box;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
