/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface;

import javax.swing.JOptionPane;
import static userInterface.PatientInfo.patient;
/**
 *
 * @author Lucia
 */
public class AlzheimerPhase extends javax.swing.JFrame {

    /**
     * Creates new form AlzheimerPhase
     */
    public AlzheimerPhase() {
        initComponents();
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        windowTitle = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Stiffness_box = new javax.swing.JComboBox<>();
        Stiffness_title = new javax.swing.JLabel();
        Hyperreflexia_check = new javax.swing.JCheckBox();
        LossPhysicalAbilities_check = new javax.swing.JCheckBox();
        Submit_button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        windowTitle.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        windowTitle.setText("Alzheimer specific symptoms");

        jLabel1.setText("Select the present symptoms:");

        Stiffness_box.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Low", "High" }));

        Stiffness_title.setText("Stiffness");

        Hyperreflexia_check.setText("Hyperreflexia");

        LossPhysicalAbilities_check.setText("Loss of physical abilities");
        LossPhysicalAbilities_check.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LossPhysicalAbilities_checkActionPerformed(evt);
            }
        });

        Submit_button.setText("Submit");
        Submit_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Submit_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LossPhysicalAbilities_check)
                    .addComponent(Hyperreflexia_check)
                    .addComponent(windowTitle)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(8, 8, 8)
                            .addComponent(Stiffness_title)
                            .addGap(27, 27, 27)
                            .addComponent(Stiffness_box, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addComponent(jLabel1)))
                .addContainerGap(137, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Submit_button)
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(windowTitle)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Stiffness_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Stiffness_title))
                .addGap(18, 18, 18)
                .addComponent(Hyperreflexia_check)
                .addGap(18, 18, 18)
                .addComponent(LossPhysicalAbilities_check)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addComponent(Submit_button)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LossPhysicalAbilities_checkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LossPhysicalAbilities_checkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LossPhysicalAbilities_checkActionPerformed

    private void Submit_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Submit_buttonActionPerformed
        String stiffnessL = (String) Stiffness_box.getSelectedItem();
        if (stiffnessL.matches("Low")) {
            patient.setStiffnessL(stiffnessL);
            patient.setStiffnessH("None");
        } else if (stiffnessL.matches("High")) {
            patient.setStiffnessL("None");
            patient.setStiffnessH(stiffnessL);
        } else {
            patient.setStiffnessL(stiffnessL);
            patient.setStiffnessH(stiffnessL);
        }
        Boolean hyperreflexia = Hyperreflexia_check.isSelected();
        if (hyperreflexia == true) {
            patient.setHyperreflexia("TRUE");
        } else {
            patient.setHyperreflexia("FALSE");
        }
        Boolean lossPhysicalAbilities = LossPhysicalAbilities_check.isSelected();
        if (lossPhysicalAbilities == true) {
            patient.setLossPhysicalAbilities("TRUE");
        } else {
            patient.setLossPhysicalAbilities("FALSE");
        }
        
        dispose();
        JOptionPane.showMessageDialog(null, "Diagnosis is: patient has ALZHEIMER PHASE ");
    }//GEN-LAST:event_Submit_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AlzheimerPhase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AlzheimerPhase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AlzheimerPhase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AlzheimerPhase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AlzheimerPhase().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox Hyperreflexia_check;
    private javax.swing.JCheckBox LossPhysicalAbilities_check;
    private javax.swing.JComboBox<String> Stiffness_box;
    private javax.swing.JLabel Stiffness_title;
    private javax.swing.JButton Submit_button;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel windowTitle;
    // End of variables declaration//GEN-END:variables
}
