/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface;

import db.interfaces.DBManager;
import db.sqlite.SQLiteDoctor;
import db.sqlite.SQLiteManager;
import dementia_dss.Doctor;
import javax.swing.JOptionPane;

/**
 *
 * @author adria
 */
public class DeleteDoctor extends javax.swing.JFrame {

    Boolean delete;
    DBManager dbManager = new SQLiteManager();
    Doctor doctor = new Doctor();

    /**
     * Creates new form DeleteDoctor
     */
    public DeleteDoctor() {
        setVisible(true);
        initComponents();
    }

    public Boolean getDelete() {
        return delete;
    }
    
    public void setDBManager (DBManager dbM) {
        this.dbManager = dbM;
    }
    
    public void setDoctor (Doctor d) {
        this.doctor = d;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        yes_button = new javax.swing.JButton();
        no_button = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        yes_button.setText("Yes");
        yes_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yes_buttonActionPerformed(evt);
            }
        });

        no_button.setText("No");
        no_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                no_buttonActionPerformed(evt);
            }
        });

        jLabel1.setText("Are you sure you want to delete the doctor?");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(yes_button)
                .addGap(65, 65, 65)
                .addComponent(no_button)
                .addGap(202, 202, 202))
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jLabel1)
                .addContainerGap(80, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(91, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yes_button)
                    .addComponent(no_button))
                .addGap(108, 108, 108))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void yes_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yes_buttonActionPerformed
        //System.out.println("Delete: " + deleteDoctor.getDelete());
        if (dbManager.getDoctorManager().doctorExists(doctor.getId()) && userPassword.checkPassword(doctor.getId(), userPassword.getPassword())) {
            dbManager.getPatientManager().deletePatientsFromDoctor(doctor);
            dbManager.getDoctorManager().deleteDoctor(doctor);
            userPassword.removeInfo();
            JOptionPane.showMessageDialog(null, "Doctor account successfully deleted.");
        } else {
            if (!dbManager.getDoctorManager().doctorExists(doctor.getId())) {
                JOptionPane.showMessageDialog(null, "The doctor does not exist, so it cannot be deleted.");
            } else if (!userPassword.checkPassword(doctor.getId(), userPassword.getPassword())) {
                JOptionPane.showMessageDialog(null, "Wrong credentials, please enter the right ones to delete the doctor account.");
            } else if (!deleteDoctor.getDelete()) {
                JOptionPane.showMessageDialog(null, "Delete canceled. ");
            }
        }
        
        /*delete = true;
        dispose();*/
    }//GEN-LAST:event_yes_buttonActionPerformed

    private void no_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_no_buttonActionPerformed
        delete = false;
        dispose();
    }//GEN-LAST:event_no_buttonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton no_button;
    private javax.swing.JButton yes_button;
    // End of variables declaration//GEN-END:variables
}
