/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface;

import db.interfaces.DBManager;
import db.sqlite.SQLiteManager;
import dementia_dss.Doctor;

/**
 *
 * @author Lucia
 */
public class Final_Window extends javax.swing.JFrame {

    DBManager dbManager = new SQLiteManager();
    Doctor doctor;

    /**
     * Creates new form Final_Window
     */
    public Final_Window(DBManager dbManager, Doctor doctor) {
        setVisible(true);
        initComponents();
        this.dbManager = dbManager;
        this.doctor = doctor;
        this.setLocationRelativeTo(null);
        System.out.println("ID de doctor en FW: " + doctor.getId());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Main_Panel = new javax.swing.JPanel();
        Buttons_Panel = new javax.swing.JPanel();
        questionLabel = new javax.swing.JLabel();
        icon = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        close_button = new javax.swing.JButton();
        loadPatient_button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(700, 600));
        setResizable(false);

        Main_Panel.setBackground(new java.awt.Color(225, 238, 238));

        Buttons_Panel.setBackground(new java.awt.Color(225, 238, 238));
        Buttons_Panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        questionLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        questionLabel.setText("Do you wish to load another patient?");

        icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/dmentiapp_lock_icon.png"))); // NOI18N

        jLabel1.setText("Data saved!");

        jSeparator1.setBackground(new java.awt.Color(0, 153, 153));

        close_button.setText("Close DMENTIAPP");
        close_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                close_buttonActionPerformed(evt);
            }
        });

        loadPatient_button.setText("Load patient");
        loadPatient_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadPatient_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Main_PanelLayout = new javax.swing.GroupLayout(Main_Panel);
        Main_Panel.setLayout(Main_PanelLayout);
        Main_PanelLayout.setHorizontalGroup(
            Main_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Buttons_Panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 711, Short.MAX_VALUE)
            .addComponent(jSeparator1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Main_PanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(loadPatient_button, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(93, 93, 93)
                .addComponent(close_button)
                .addGap(192, 192, 192))
            .addGroup(Main_PanelLayout.createSequentialGroup()
                .addGroup(Main_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Main_PanelLayout.createSequentialGroup()
                        .addGap(228, 228, 228)
                        .addComponent(icon)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1))
                    .addGroup(Main_PanelLayout.createSequentialGroup()
                        .addGap(207, 207, 207)
                        .addComponent(questionLabel)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Main_PanelLayout.setVerticalGroup(
            Main_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Main_PanelLayout.createSequentialGroup()
                .addGroup(Main_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Main_PanelLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(icon)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Main_PanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(51, 51, 51)))
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                .addComponent(questionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(Main_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(close_button)
                    .addComponent(loadPatient_button))
                .addGap(84, 84, 84)
                .addComponent(Buttons_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(Main_Panel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void close_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_close_buttonActionPerformed
        dbManager.disconnect();
        this.dispose();
        System.exit(0);
    }//GEN-LAST:event_close_buttonActionPerformed

    private void loadPatient_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadPatient_buttonActionPerformed
        this.dispose();
        new Principal_Window(dbManager, doctor);
    }//GEN-LAST:event_loadPatient_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Buttons_Panel;
    private javax.swing.JPanel Main_Panel;
    private javax.swing.JButton close_button;
    private javax.swing.JLabel icon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton loadPatient_button;
    private javax.swing.JLabel questionLabel;
    // End of variables declaration//GEN-END:variables
}
