/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface;

import db.interfaces.DBManager;
import db.sqlite.SQLiteManager;
import dementia_dss.Doctor;

/**
 *
 * @author Lucia
 */
public class Final_Window extends javax.swing.JFrame {

    DBManager dbManager = new SQLiteManager();
    Doctor doctor = new Doctor();

    /**
     * Creates new form Final_Window
     */
    public Final_Window(DBManager dbManager, Doctor doctor) {
        setVisible(true);
        initComponents();
        this.dbManager = dbManager;
        this.doctor = doctor;
        questionLabel.setText("Do you want to save the data?");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Main_Panel = new javax.swing.JPanel();
        Buttons_Panel = new javax.swing.JPanel();
        loadPatient_button = new javax.swing.JButton();
        close_button = new javax.swing.JButton();
        questionLabel = new javax.swing.JLabel();
        icon = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        Main_Panel.setBackground(new java.awt.Color(225, 238, 238));

        Buttons_Panel.setBackground(new java.awt.Color(225, 238, 238));
        Buttons_Panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        loadPatient_button.setText("Load patient");
        loadPatient_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadPatient_buttonActionPerformed(evt);
            }
        });
        Buttons_Panel.add(loadPatient_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 160, -1));

        close_button.setText("Close DMENTIAPP");
        close_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                close_buttonActionPerformed(evt);
            }
        });
        Buttons_Panel.add(close_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, -1, -1));

        questionLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        questionLabel.setText("Do you wish to load another patient?");

        icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/dmentiapp_lock_icon.png"))); // NOI18N

        jLabel1.setText("Data saved!");

        jSeparator1.setBackground(new java.awt.Color(0, 153, 153));

        javax.swing.GroupLayout Main_PanelLayout = new javax.swing.GroupLayout(Main_Panel);
        Main_Panel.setLayout(Main_PanelLayout);
        Main_PanelLayout.setHorizontalGroup(
            Main_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Buttons_Panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 457, Short.MAX_VALUE)
            .addComponent(jSeparator1)
            .addGroup(Main_PanelLayout.createSequentialGroup()
                .addGroup(Main_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Main_PanelLayout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(icon)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1))
                    .addGroup(Main_PanelLayout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(questionLabel)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Main_PanelLayout.setVerticalGroup(
            Main_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Main_PanelLayout.createSequentialGroup()
                .addGroup(Main_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Main_PanelLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jLabel1)
                        .addGap(49, 49, 49))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Main_PanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(icon)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(questionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Buttons_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(Main_Panel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void close_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_close_buttonActionPerformed
        dbManager.disconnect();
        this.dispose();
        System.exit(0);
    }//GEN-LAST:event_close_buttonActionPerformed

    private void loadPatient_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadPatient_buttonActionPerformed
        this.dispose();
        new Principal_Window(dbManager, doctor);
    }//GEN-LAST:event_loadPatient_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Buttons_Panel;
    private javax.swing.JPanel Main_Panel;
    private javax.swing.JButton close_button;
    private javax.swing.JLabel icon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton loadPatient_button;
    private javax.swing.JLabel questionLabel;
    // End of variables declaration//GEN-END:variables
}
