/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface;

/*
Welcome to NOMBRE,

This decision support system will help you make the most
accurate diagnosis for dementia or possible dementia patients.
The program is able to diagnose Alzheimer, Parkinson and
vascular disease. It will also help in determining which phase
of the disease is the pacient facing.
In order to make the most of it, please, fill the personal
information of the patient and select which symptoms does he/she
have. The symptoms will be divided into general symptoms,
motor symptoms and other pathologies in order to ease the
process.
Finally, remember that this is only extra help for providing
the best service to the patients, but the last decision is
taken by you, the clinician.

Thank you for using NOMBRE
 */
/**
 *
 * @author adria
 */
public class Initial_Description extends javax.swing.JPanel {

    /**
     * Creates new form Initial_Description
     */
    public Initial_Description() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(225, 238, 238));
        setPreferredSize(new java.awt.Dimension(700, 777));
        setRequestFocusEnabled(false);

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("\n\nWelcome to NOMBRE.\n\nThis decision support system will help you make the most accurate diagnosis for dementia\nor possible dementia patients. The program is able to diagnose Alzheimer, Parkinson and \nvascular disease. It will also help in determining which phase of the disease is the \npacient facing.\nIn order to make the most of it, please, fill the personal information of the patient and\nselect which symptoms does he/she have. The symptoms will be divided into general symptoms,\nmotor symptoms and other pathologies in order to ease the process. \nFinally, remember that this is only extra help for providing the best service to the \npatients, but the last decision is taken by you, the clinician.\n\nThank you for using NOMBRE.");
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1218, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 593, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
