/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface;

import dementia_dss.Patient;

/**
 *
 * @author adria
 */
public class Other_Pathologies extends javax.swing.JPanel {

    Patient patient = new Patient();

    /**
     * Creates new form Other_Pathologies
     */
    public Other_Pathologies() {
        initComponents();
    }

    public Other_Pathologies(Patient patient) {
        this.patient = patient;
        initComponents();
        setVisible(true);

        if (patient.getDownSyndrome().equalsIgnoreCase("TRUE")) {
            DownSyndrome_check.setSelected(true);
        }
        if (patient.getHyperglycemia().equalsIgnoreCase("TRUE")) {
            Hyperglycemia_check.setSelected(true);
        }
        if (patient.getHyperlipidemia().equalsIgnoreCase("TRUE")) {
            Hyperlypidemia_check.setSelected(true);
        }
        if (patient.getInsulin().equalsIgnoreCase("TRUE")) {
            Insulin_check.setSelected(true);
        }
        if (patient.getHypertension().equalsIgnoreCase("TRUE")) {
            Hypertension_check.setSelected(true);
        }
        if (patient.getHeartCerebro().equalsIgnoreCase("TRUE")) {
            HeartAttacks_check.setSelected(true);
        }
        if (patient.getDiabetes().equalsIgnoreCase("TRUE")) {
            Diabetes_check.setSelected(true);
        }
        if (patient.getObesity().equalsIgnoreCase("TRUE")) {
            Obesity_check.setSelected(true);
        }
        if (patient.getCholesterol().equalsIgnoreCase("TRUE")) {
            Cholesterol_check.setSelected(true);
        }
        if (patient.getArteriosclerosis().equalsIgnoreCase("TRUE")) {
            Arteriosclerosis_check.setSelected(true);
        }
        if (patient.getDepression().equalsIgnoreCase("TRUE")) {
            Depression_check.setSelected(true);
        }
    }

    public void SaveInfo() {
        Boolean downSyndrome = this.DownSyndrome_check.isSelected();
        if (downSyndrome) {
            patient.setDownSyndrome("TRUE");
        } else {
            patient.setDownSyndrome("FALSE");
        }
        Boolean hyperglycemia = this.Hyperglycemia_check.isSelected();
        if (hyperglycemia) {
            patient.setHyperglycemia("TRUE");
        } else {
            patient.setHyperglycemia("FALSE");
        }
        Boolean insulin = this.Insulin_check.isSelected();
        if (insulin) {
            patient.setInsulin("TRUE");
        } else {
            patient.setInsulin("FALSE");
        }
        Boolean hyperlipidemia = this.Hyperlypidemia_check.isSelected();
        if (hyperlipidemia) {
            patient.setHyperlipidemia("TRUE");
        } else {
            patient.setHyperlipidemia("FALSE");
        }
        Boolean hypertension = this.Hypertension_check.isSelected();
        if (hypertension) {
            patient.setHypertension("TRUE");
        } else {
            patient.setHypertension("FALSE");
        }
        Boolean heartCerebro = this.HeartAttacks_check.isSelected();
        if (heartCerebro) {
            patient.setHeartCerebro("TRUE");
        } else {
            patient.setHeartCerebro("FALSE");
        }
        Boolean diabetes = this.Diabetes_check.isSelected();
        if (diabetes) {
            patient.setDiabetes("TRUE");
        } else {
            patient.setDiabetes("FALSE");
        }
        Boolean obesity = this.Obesity_check.isSelected();
        if (obesity) {
            patient.setObesity("TRUE");
        } else {
            patient.setObesity("FALSE");
        }
        Boolean cholesterol = this.Cholesterol_check.isSelected();
        if (cholesterol) {
            patient.setCholesterol("TRUE");
        } else {
            patient.setCholesterol("FALSE");
        }
        Boolean arteriosclerosis = this.Arteriosclerosis_check.isSelected();
        if (arteriosclerosis) {
            patient.setArteriosclerosis("TRUE");
        } else {
            patient.setArteriosclerosis("FALSE");
        }
        Boolean depression = this.Depression_check.isSelected();
        if (depression) {
            patient.setDepression("TRUE");
        } else {
            patient.setDepression("FALSE");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        DownSyndrome_check = new javax.swing.JCheckBox();
        Hyperglycemia_check = new javax.swing.JCheckBox();
        Hyperlypidemia_check = new javax.swing.JCheckBox();
        Hypertension_check = new javax.swing.JCheckBox();
        Insulin_check = new javax.swing.JCheckBox();
        Diabetes_check = new javax.swing.JCheckBox();
        Obesity_check = new javax.swing.JCheckBox();
        HeartAttacks_check = new javax.swing.JCheckBox();
        Cholesterol_check = new javax.swing.JCheckBox();
        Arteriosclerosis_check = new javax.swing.JCheckBox();
        Depression_check = new javax.swing.JCheckBox();

        setMaximumSize(new java.awt.Dimension(1345, 671));
        setPreferredSize(new java.awt.Dimension(1260, 777));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Other pathologies");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(485, 21, -1, -1));

        jLabel2.setText("Please, mark other pathologies the patient have:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 68, -1, -1));

        DownSyndrome_check.setText("Down Syndrome");
        DownSyndrome_check.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DownSyndrome_checkActionPerformed(evt);
            }
        });
        add(DownSyndrome_check, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 160, -1, -1));

        Hyperglycemia_check.setText("Hyperglicemia");
        add(Hyperglycemia_check, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 284, -1, -1));

        Hyperlypidemia_check.setText("Hyperlipidemia");
        add(Hyperlypidemia_check, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 412, -1, -1));

        Hypertension_check.setText("Arterial hypertension");
        add(Hypertension_check, new org.netbeans.lib.awtextra.AbsoluteConstraints(454, 160, -1, -1));

        Insulin_check.setText("Insulin resistance");
        add(Insulin_check, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 537, -1, -1));

        Diabetes_check.setText("Diabetes");
        add(Diabetes_check, new org.netbeans.lib.awtextra.AbsoluteConstraints(454, 284, -1, -1));

        Obesity_check.setText("Obesity");
        add(Obesity_check, new org.netbeans.lib.awtextra.AbsoluteConstraints(454, 412, -1, -1));

        HeartAttacks_check.setText("Recorded heart/cerebrovascular attacks");
        add(HeartAttacks_check, new org.netbeans.lib.awtextra.AbsoluteConstraints(454, 537, -1, -1));

        Cholesterol_check.setText("High cholesterol");
        add(Cholesterol_check, new org.netbeans.lib.awtextra.AbsoluteConstraints(989, 160, -1, -1));

        Arteriosclerosis_check.setText("Ateriosclerosis");
        add(Arteriosclerosis_check, new org.netbeans.lib.awtextra.AbsoluteConstraints(989, 284, -1, -1));

        Depression_check.setText("Depression");
        add(Depression_check, new org.netbeans.lib.awtextra.AbsoluteConstraints(989, 412, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void DownSyndrome_checkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DownSyndrome_checkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DownSyndrome_checkActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox Arteriosclerosis_check;
    private javax.swing.JCheckBox Cholesterol_check;
    private javax.swing.JCheckBox Depression_check;
    private javax.swing.JCheckBox Diabetes_check;
    private javax.swing.JCheckBox DownSyndrome_check;
    private javax.swing.JCheckBox HeartAttacks_check;
    private javax.swing.JCheckBox Hyperglycemia_check;
    private javax.swing.JCheckBox Hyperlypidemia_check;
    private javax.swing.JCheckBox Hypertension_check;
    private javax.swing.JCheckBox Insulin_check;
    private javax.swing.JCheckBox Obesity_check;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables

}
