/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface;

import dementia_dss.Patient;

/**
 *
 * @author adria
 */
public class Parkinson_Phase extends javax.swing.JPanel {

    Patient patient = new Patient();

    /**
     * Creates new form Parkinson_Phase
     */
    public Parkinson_Phase() {
        initComponents();
    }

    public Parkinson_Phase(Patient patient) {
        this.patient = patient;
        initComponents();
        Boolean lossPhysicalAbilities = LossPhysicalAbilities_check.isSelected();
        if (lossPhysicalAbilities) {
            patient.setLossPhysicalAbilities("TRUE");
        } else {
            patient.setLossPhysicalAbilities("FALSE");
        }
        String tremor = (String) Tremor_box.getSelectedItem();
        if (tremor.equals("Unilateral")) {
            patient.setTremorUni("TRUE");
            patient.setTremorBi("FALSE");
        } else if (tremor.equals("Bilateral")) {
            patient.setTremorUni("FALSE");
            patient.setTremorBi("TRUE");
        } else {
            patient.setTremorUni("FALSE");
            patient.setTremorBi("FALSE");
        }
    }

    public void SaveInfo() {
        Boolean physicalAbilities = this.LossPhysicalAbilities_check.isSelected();
        if (physicalAbilities) {
            patient.setLossPhysicalAbilities("TRUE");
        } else {
            patient.setLossPhysicalAbilities("FALSE");
        }
        if (physicalAbilities) {
            patient.setLossPhysicalAbilities("TRUE");
        } else {
            patient.setLossPhysicalAbilities("FALSE");
        }
        if (Tremor_box.getSelectedItem().equals("Unilateral")) {
            patient.setTremorUni("TRUE");
            patient.setTremorBi("FALSE"); // Lo ponemos a false o lo dejamos en true porque si es high tb es low?
        } else if (Tremor_box.getSelectedItem().equals("Bilateral")) {
            patient.setTremorUni("FALSE");
            patient.setTremorBi("TRUE");
        } else if (Tremor_box.getSelectedItem().equals("None")) {
            patient.setTremorBi("FALSE");
            patient.setTremorUni("FALSE");
            patient.setTremor("FALSE");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Tremor_box = new javax.swing.JComboBox<>();
        LossPhysicalAbilities_check = new javax.swing.JCheckBox();

        setPreferredSize(new java.awt.Dimension(1260, 777));

        jLabel1.setText("Parkinson Specific Symptoms");

        jLabel2.setText("Please, mark the present symptoms for the system to be able to estimate the phase:");

        jLabel3.setText("Tremor");

        Tremor_box.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Unilateral", "Bilateral" }));

        LossPhysicalAbilities_check.setText("Loss of physical abilities");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(287, 287, 287)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LossPhysicalAbilities_check)
                                .addGap(289, 289, 289)
                                .addComponent(jLabel3)
                                .addGap(74, 74, 74)
                                .addComponent(Tremor_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2))))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Tremor_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LossPhysicalAbilities_check))
                .addContainerGap(383, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox LossPhysicalAbilities_check;
    private javax.swing.JComboBox<String> Tremor_box;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
