/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface;

import dementia_dss.Patient;

/**
 *
 * @author adria
 */
public class Patient_Info extends javax.swing.JPanel {

    Patient patient = new Patient();

    /**
     * Creates new form Patient_Info
     */
    public Patient_Info() {
        initComponents();
    }

    public Patient_Info(Patient patient) {
        this.patient = patient;
        initComponents();
        setVisible(true);

        if (patient != null) {
            if (!patient.getName().equalsIgnoreCase("")) {
                NameSurname_enter.setText(patient.getName());
            }
            if (patient.getAge() != 0) {
                Age_enter.setText(Integer.toString(patient.getAge()));
            }
            if (!patient.getSex().equalsIgnoreCase("")) {
                if (patient.getSex().matches("Male")) {
                    Sex_box.setSelectedIndex(0);
                } else {
                    Sex_box.setSelectedIndex(1);
                }
            }
        }

    }

    public void SaveInfo() { // REVISAR QUE ESTE BIEN
        if (NameSurname_enter.getText() != null) {
            patient.setName(NameSurname_enter.getText());
        }
        if (Age_enter.getText() != null) {
            patient.setAge(Integer.parseInt(Age_enter.getText()));
        }
        if (Sex_box.getSelectedItem().equals("Male")) {
            patient.setSex("MALE");
        } else {
            patient.setSex("FEMALE");
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Name_Surname = new javax.swing.JLabel();
        Age = new javax.swing.JLabel();
        Sex = new javax.swing.JLabel();
        Sex_box = new javax.swing.JComboBox<>();
        NameSurname_enter = new javax.swing.JTextField();
        Age_enter = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1260, 777));

        Name_Surname.setText("Name and surname:");

        Age.setText("Age");

        Sex.setText("Sex: ");

        Sex_box.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));

        jLabel4.setText("Patient Information");

        jLabel5.setText("Please, fill in the personal information about the patient:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(432, 432, 432)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Age)
                                .addComponent(Name_Surname)
                                .addComponent(Sex)))
                        .addGap(71, 71, 71)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Age_enter, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Sex_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NameSurname_enter, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(235, 329, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel4)
                .addGap(23, 23, 23)
                .addComponent(jLabel5)
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Name_Surname)
                    .addComponent(NameSurname_enter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Age)
                    .addComponent(Age_enter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Sex_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Sex))
                .addContainerGap(351, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Age;
    private javax.swing.JTextField Age_enter;
    private javax.swing.JTextField NameSurname_enter;
    private javax.swing.JLabel Name_Surname;
    private javax.swing.JLabel Sex;
    private javax.swing.JComboBox<String> Sex_box;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
