/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface;

import dementia_dss.Patient;
import javax.swing.ImageIcon;

/**
 *
 * @author adria
 */
public class Patient_Info extends javax.swing.JPanel {

    Patient patient = new Patient();

    /**
     * Creates new form Patient_Info
     */
    public Patient_Info() {
        initComponents();        
    }

    public Patient_Info(Patient patient) {
        this.patient = patient;
        initComponents();
        setVisible(true);

        if (patient != null) {
            if (!patient.getName().equalsIgnoreCase("")) {
                NameSurname_enter.setText(patient.getName());
            }
            if (patient.getAge() != 0) {
                Age_enter.setText(Integer.toString(patient.getAge()));
            }
            if (!patient.getSex().equalsIgnoreCase("")) {
                if (patient.getSex().matches("Male")) {
                    Sex_box.setSelectedIndex(0);
                } else {
                    Sex_box.setSelectedIndex(1);
                }
            }
        }

    }

    public void SaveInfo() { // REVISAR QUE ESTE BIEN
        if (NameSurname_enter.getText() != null) {
            patient.setName(NameSurname_enter.getText());
        }
        if (Age_enter.getText() != null) {
            patient.setAge(Integer.parseInt(Age_enter.getText()));
        }
        if (Sex_box.getSelectedItem().equals("Male")) {
            patient.setSex("MALE");
        } else {
            patient.setSex("FEMALE");
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Name_Surname = new javax.swing.JLabel();
        Age = new javax.swing.JLabel();
        Sex = new javax.swing.JLabel();
        Sex_box = new javax.swing.JComboBox<>();
        NameSurname_enter = new javax.swing.JTextField();
        Age_enter = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        iconoMarca = new javax.swing.JLabel();

        setBackground(new java.awt.Color(173, 230, 230));
        setPreferredSize(new java.awt.Dimension(1260, 777));

        Name_Surname.setText("Name and surname:");

        Age.setText("Age");

        Sex.setText("Sex: ");

        Sex_box.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));

        Age_enter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Age_enterActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setText("PATIENT INFORMATION");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Please, fill in the personal information about the patient:");

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        iconoMarca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userInterface/dmentiapp_logo1.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(iconoMarca))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addComponent(iconoMarca))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(184, 184, 184)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Age)
                            .addComponent(Name_Surname)
                            .addComponent(Sex))
                        .addGap(71, 71, 71)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Age_enter, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Sex_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NameSurname_enter, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel5))
                .addContainerGap(516, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Name_Surname)
                    .addComponent(NameSurname_enter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Age)
                    .addComponent(Age_enter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Sex)
                    .addComponent(Sex_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(439, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void Age_enterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Age_enterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Age_enterActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Age;
    private javax.swing.JTextField Age_enter;
    private javax.swing.JTextField NameSurname_enter;
    private javax.swing.JLabel Name_Surname;
    private javax.swing.JLabel Sex;
    private javax.swing.JComboBox<String> Sex_box;
    private javax.swing.JLabel iconoMarca;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
