/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author adria
 */
public class Principal_prueba extends javax.swing.JFrame implements ActionListener {

    Panel1 panel1 = new Panel1();
    Panel2 panel2 = new Panel2();
    Panel3 panel3 = new Panel3();
    Panel4 panel4 = new Panel4();

    /**
     * Creates new form Principal_prueba
     */
    public Principal_prueba() {
        initComponents();

        Contenedor.add(panel1);

        panel1.setVisible(true);
        panel2.setVisible(false);
        panel3.setVisible(false);
        panel4.setVisible(false);

        deshabilitarBotones();

        //Next_button.addActionListener(this);
        //Back_button.addActionListener(this);
    }

    public void deshabilitarBotones() {
        if (panel1.isVisible()) {
            Back_button.setEnabled(false);
            Next_button.setEnabled(true);
        } else if (panel2.isVisible() || panel3.isVisible()) {
            Back_button.setEnabled(true);
            Next_button.setEnabled(true);
        } else if (panel4.isVisible()) {
            Back_button.setEnabled(true);
            Next_button.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Contenedor = new javax.swing.JPanel();
        Back_button = new javax.swing.JButton();
        Next_button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        Contenedor.setPreferredSize(new java.awt.Dimension(1100, 700));
        Contenedor.setLayout(new java.awt.GridBagLayout());

        Back_button.setText("Back");
        Back_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Back_buttonActionPerformed(evt);
            }
        });
        Contenedor.add(Back_button, new java.awt.GridBagConstraints());

        Next_button.setText("Next");
        Next_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Next_buttonActionPerformed(evt);
            }
        });
        Contenedor.add(Next_button, new java.awt.GridBagConstraints());

        getContentPane().add(Contenedor, new java.awt.GridBagConstraints());

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Next_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Next_buttonActionPerformed
        // TODO add your handling code here:
        if (panel1.isVisible()) {
            panel1.setVisible(false);
            panel2.setVisible(true);
            panel3.setVisible(false);
            panel4.setVisible(false);
            Contenedor.add(panel2);
        } else if (panel2.isVisible()) {
            panel1.setVisible(false);
            panel2.setVisible(false);
            panel3.setVisible(true);
            panel4.setVisible(false);
            Contenedor.add(panel3);
        } else if (panel3.isVisible()) {
            panel1.setVisible(false);
            panel2.setVisible(false);
            panel3.setVisible(false);
            panel4.setVisible(true);
            Contenedor.add(panel4);
        }
        Contenedor.validate();
        deshabilitarBotones();
    }//GEN-LAST:event_Next_buttonActionPerformed

    private void Back_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Back_buttonActionPerformed
        // TODO add your handling code here:
        if (panel2.isVisible()) {
            panel1.setVisible(true);
            panel2.setVisible(false);
            panel3.setVisible(false);
            panel4.setVisible(false);
            Contenedor.add(panel1);
        } else if (panel3.isVisible()) {
            panel1.setVisible(false);
            panel2.setVisible(true);
            panel3.setVisible(false);
            panel4.setVisible(false);
            Contenedor.add(panel2);
        } else if (panel4.isVisible()) {
            panel1.setVisible(false);
            panel2.setVisible(false);
            panel3.setVisible(true);
            panel4.setVisible(false);

            Contenedor.add(panel3);
        }

        Contenedor.validate();
        deshabilitarBotones();
    }//GEN-LAST:event_Back_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal_prueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal_prueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal_prueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal_prueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal_prueba().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back_button;
    private javax.swing.JPanel Contenedor;
    private javax.swing.JButton Next_button;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent ae) {
//        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
